name=com.instaclustr.transformer.clickhouse.ClickHouseMemorySink
endpoint=http://172.19.0.3:8123
username=clickhouse
password=clickhouse
database=clickhouse_db
table=shuffled_text
sink_model=async_byte_buffer
max_rows_before_sink=200000
