name=com.instaclustr.transformer.clickhouse.ClickHouseFileSink
endpoint=http://172.19.0.3:8123
username=clickhouse
password=clickhouse
database=clickhouse_db
table=shuffled_text
remove_file_after_processed=true